#!/usr/bin/env Rscript

library(ggplot2)

args <- commandArgs(trailingOnly = TRUE)

#ld density plot
d <- read.table(args[1], header=TRUE)

colnames(d)

png(paste(args[1], 'ld.density.png', sep=''))
plot(density(d$ld))
dev.off()

png(paste(args[1], 'ld.linkage.png', sep=''), width=2000)
ggplot( d, aes(x=pos,y=apos-pos, color=cut(ld, breaks=c(-1,-0.5, 0.5, 1)))) + geom_point(size=2)
dev.off()



